version: "3.8" # 最新のバージョンに更新

services:
  next:
    container_name: chrono-navi-next-local
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    restart: always
    volumes:
      - ./apps/web/app:/app/apps/web/app
      - ./apps/web/public:/app/apps/web/public
      - ./apps/web/.next:/app/apps/web/.next
      - ./apps/admin/app:/app/apps/admin/app
      - ./apps/admin/public:/app/apps/admin/public
      - ./apps/admin/.next:/app/apps/admin/.next
    ports:
      - "3000:3000"
      - "3001:3001"
    command: >
      sh -c "pnpm dev"

networks:
  default:
    name: timenavi-net-local
