version: "3.8" # 最新のバージョンに更新

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    restart: always
    volumes:
      - ./apps/web/app:/app/apps/web/app
      - ./apps/web/node_modules:/app/apps/web/node_modules
      - ./apps/web/.next:/app/apps/web/.next
    ports:
      - "3000:3000"

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile.dev
    restart: always
    volumes:
      - ./apps/admin/app:/app/apps/admin/app
      - ./apps/admin/node_modules:/app/apps/admin/node_modules
      - ./apps/admin/.next:/app/apps/admin/.next
    ports:
      - "3001:3001"

networks:
  default:
    name: timenavi-net-local
