FROM node:18-alpine

# apk updateを実行して、libc6-compatをインストールする
RUN apk update && apk add --no-cache libc6-compat

# pnpmをインストール
RUN npm install -g pnpm

ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

COPY package.json ./
COPY pnpm-workspace.yaml ./

RUN pnpm -g add turbo

COPY . .
COPY ./apps/docs/next.config.js ./next.config.js

EXPOSE 3001

CMD ["pnpm", "dev"]