name: Run Biome

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

env:
  BUN_VERSION: 1.1.42

jobs:
  check-biome:
    name: 'Check Biome'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies
        run: bun install
        env:
          BUN_CACHE: ${{ github.workspace }}/.bun-cache

      - name: Run Biome
        run: biome ci