name: Run Biome

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check-biome:
    name: 'Check Biome'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.4

      - name: Run Biome
        run: biome ci .