name: Run Biome

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

env:
  BUN_VERSION: 1.1.42

jobs:
  check-biome:
    name: 'Check Biome'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci