name: CI

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize

jobs:
  biome-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.4

      - name: Run
        run: biome ci .

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run
        run: pnpm check-types